In [4]:
import numpy as np

In [5]:
x = np.array([ [1,2,3], [4,5,6] ])

In [6]:
# Chapter #2: NumPy build-in methods

In [7]:
x = np.random.rand(20)
x

array([0.97316575, 0.09288354, 0.22162799, 0.47245147, 0.53208261,
       0.87912189, 0.56385863, 0.68658764, 0.21268875, 0.8141132 ,
       0.01925957, 0.80788237, 0.58194071, 0.46061975, 0.91240694,
       0.41810326, 0.30277832, 0.60825458, 0.47862148, 0.2042153 ])

In [9]:
x = np.random.randint(1, 50)
x

11

In [10]:
x = np.random.randint(1, 50, 10)
x

array([27,  7,  4, 21, 24, 11, 21,  7,  7,  5])

In [11]:
x = np.arange(1, 30)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [12]:
x = np.eye(7)
x

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [13]:
x = np.ones((7, 7))
x

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [14]:
x = np.zeros(8)
x

array([0., 0., 0., 0., 0., 0., 0., 0.])

MINI CHALLENGE #2:
- Write a code that takes in a positive integer "x" from the user and creates a 1x10 array with random numbers ranging from 0 to "x"

In [15]:
x = int(input("Please enter a positive integer"))

In [16]:
x

30

In [17]:
x = np.random.randint(1, x, 30)
x

array([14,  9, 21, 19,  6, 12, 25, 27, 20, 19, 20, 18, 23,  9, 20,  2, 22,
       12,  2,  8,  2, 10,  3, 11, 13,  1,  8,  5, 10,  7])

TASK #3: PERFORM MATHEMATICAL OPERATIONS IN NUMPY

In [19]:
x = np.arange(1, 10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
y = np.arange(1,10)
y

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
sum = x + y
sum

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [22]:
squared = x ** 2
squared

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [23]:
sqrt = np.sqrt(squared)
sqrt

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [24]:
z = np.exp(y)
z

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [25]:
x = np.array([5, 7, 20])
y = np.array([9, 15, 4])

In [29]:
distance = np.linalg.norm(x - y)
distance

18.33030277982336

In [31]:
distance = np.sqrt(x ** 2 + y ** 2)
distance

array([10.29563014, 16.55294536, 20.39607805])

TASK #4: PERFORM ARRAYS SLICING AND INDEXING

In [32]:
my_numpy_array = np.array([3, 5, 6, 2, 8, 10, 20, 50])
my_numpy_array

array([ 3,  5,  6,  2,  8, 10, 20, 50])

In [33]:
my_numpy_array[0]

3

In [37]:
my_numpy_array[-1]

50

In [38]:
my_numpy_array[0:3]

array([3, 5, 6])

In [42]:
my_numpy_array[0:-1]

array([ 3,  5,  6,  2,  8, 10, 20])

In [43]:
my_numpy_array[0:]

array([ 3,  5,  6,  2,  8, 10, 20, 50])

In [44]:
# Broadcasting, altering several values in a numpy array at once
my_numpy_array[0:4] = 7
my_numpy_array

array([ 7,  7,  7,  7,  8, 10, 20, 50])

In [45]:
matrix = np.random.randint(1, 10, (4, 4))
matrix

array([[5, 8, 3, 3],
       [5, 7, 5, 3],
       [2, 5, 3, 6],
       [8, 9, 8, 2]])

In [46]:
# first row in a matrix:
matrix[0]

array([5, 8, 3, 3])

In [49]:
# First column in matrix:
matrix[:, 0]

array([5, 5, 2, 8])

In [50]:
# Get one element
matrix[0][2]

3

In [53]:
# Replace the last row with 0:
X = np.array([
    [2, 30, 20, -2, 4],
    [3, 4, 40, -3, -2],
    [-3, 4, -6, 90,10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])
X

array([[ 2, 30, 20, -2,  4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [13, 24, 22, 32, 37]])

In [55]:
X[-1] = 0
X

array([[ 2, 30, 20, -2,  4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [ 0,  0,  0,  0,  0]])

TASK #5: PERFORM ELEMENTS SELECTION (CONDITIONAL)

In [56]:
matrix = np.random.randint(1, 10, (5, 5))
matrix

array([[5, 6, 4, 4, 4],
       [9, 2, 4, 8, 2],
       [9, 1, 4, 2, 8],
       [6, 8, 5, 4, 7],
       [9, 7, 7, 3, 1]])

In [59]:
# Filter some elements
new_matrix = matrix[ matrix > 7 ]
new_matrix

array([9, 8, 9, 8, 8, 9])

In [65]:
# obtain odd elements only
new_matrix = matrix[ matrix % 2 == 1 ]
new_matrix

array([5, 9, 9, 1, 5, 7, 9, 7, 7, 3, 1])

MINI CHALLENGE #5:

In the following matrix, replace negative elements by 0 and replace odd elements with -2

In [66]:
X = np.array([
    [2, 30, 20, -2, 4],
    [3, 4, 40, -3, -2],
    [-3, 4, -6, 90,10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])
X

array([[ 2, 30, 20, -2,  4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [13, 24, 22, 32, 37]])

In [67]:
X[X < 0] = 0
X

array([[ 2, 30, 20,  0,  4],
       [ 3,  4, 40,  0,  0],
       [ 0,  4,  0, 90, 10],
       [25, 45, 34, 22, 12],
       [13, 24, 22, 32, 37]])

In [68]:
X[X % 2 == 1] = -2
X

array([[ 2, 30, 20,  0,  4],
       [-2,  4, 40,  0,  0],
       [ 0,  4,  0, 90, 10],
       [-2, -2, 34, 22, 12],
       [-2, 24, 22, 32, -2]])