In [4]:
from _curses import raw

import numpy as np

In [5]:
x = np.array([ [1,2,3], [4,5,6] ])

In [6]:
# Chapter #2: NumPy build-in methods

In [7]:
x = np.random.rand(20)
x

array([0.97316575, 0.09288354, 0.22162799, 0.47245147, 0.53208261,
       0.87912189, 0.56385863, 0.68658764, 0.21268875, 0.8141132 ,
       0.01925957, 0.80788237, 0.58194071, 0.46061975, 0.91240694,
       0.41810326, 0.30277832, 0.60825458, 0.47862148, 0.2042153 ])

In [9]:
x = np.random.randint(1, 50)
x

11

In [10]:
x = np.random.randint(1, 50, 10)
x

array([27,  7,  4, 21, 24, 11, 21,  7,  7,  5])

In [11]:
x = np.arange(1, 30)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [12]:
x = np.eye(7)
x

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [13]:
x = np.ones((7, 7))
x

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [14]:
x = np.zeros(8)
x

array([0., 0., 0., 0., 0., 0., 0., 0.])

MINI CHALLENGE #2:
- Write a code that takes in a positive integer "x" from the user and creates a 1x10 array with random numbers ranging from 0 to "x"

In [15]:
x = int(input("Please enter a positive integer"))

In [16]:
x

30

In [17]:
x = np.random.randint(1, x, 30)
x

array([14,  9, 21, 19,  6, 12, 25, 27, 20, 19, 20, 18, 23,  9, 20,  2, 22,
       12,  2,  8,  2, 10,  3, 11, 13,  1,  8,  5, 10,  7])

TASK #3: PERFORM MATHEMATICAL OPERATIONS IN NUMPY

In [19]:
x = np.arange(1, 10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
y = np.arange(1,10)
y

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
sum = x + y
sum

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [22]:
squared = x ** 2
squared

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [23]:
sqrt = np.sqrt(squared)
sqrt

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [24]:
z = np.exp(y)
z

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [25]:
x = np.array([5, 7, 20])
y = np.array([9, 15, 4])

In [29]:
distance = np.linalg.norm(x - y)
distance

18.33030277982336

In [31]:
distance = np.sqrt(x ** 2 + y ** 2)
distance

array([10.29563014, 16.55294536, 20.39607805])

# TASK #4: PERFORM ARRAYS SLICING AND INDEXING

In [32]:
my_numpy_array = np.array([3, 5, 6, 2, 8, 10, 20, 50])
my_numpy_array

array([ 3,  5,  6,  2,  8, 10, 20, 50])

In [33]:
my_numpy_array[0]

3

In [37]:
my_numpy_array[-1]

50

In [38]:
my_numpy_array[0:3]

array([3, 5, 6])

In [42]:
my_numpy_array[0:-1]

array([ 3,  5,  6,  2,  8, 10, 20])

In [43]:
my_numpy_array[0:]

array([ 3,  5,  6,  2,  8, 10, 20, 50])

In [44]:
# Broadcasting, altering several values in a numpy array at once
my_numpy_array[0:4] = 7
my_numpy_array

array([ 7,  7,  7,  7,  8, 10, 20, 50])

In [45]:
matrix = np.random.randint(1, 10, (4, 4))
matrix

array([[5, 8, 3, 3],
       [5, 7, 5, 3],
       [2, 5, 3, 6],
       [8, 9, 8, 2]])

In [46]:
# first row in a matrix:
matrix[0]

array([5, 8, 3, 3])

In [49]:
# First column in matrix:
matrix[:, 0]

array([5, 5, 2, 8])

In [50]:
# Get one element
matrix[0][2]

3

In [53]:
# Replace the last row with 0:
X = np.array([
    [2, 30, 20, -2, 4],
    [3, 4, 40, -3, -2],
    [-3, 4, -6, 90,10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])
X

array([[ 2, 30, 20, -2,  4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [13, 24, 22, 32, 37]])

In [55]:
X[-1] = 0
X

array([[ 2, 30, 20, -2,  4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [ 0,  0,  0,  0,  0]])

# TASK #5: PERFORM ELEMENTS SELECTION (CONDITIONAL)

In [56]:
matrix = np.random.randint(1, 10, (5, 5))
matrix

array([[5, 6, 4, 4, 4],
       [9, 2, 4, 8, 2],
       [9, 1, 4, 2, 8],
       [6, 8, 5, 4, 7],
       [9, 7, 7, 3, 1]])

In [59]:
# Filter some elements
new_matrix = matrix[ matrix > 7 ]
new_matrix

array([9, 8, 9, 8, 8, 9])

In [65]:
# obtain odd elements only
new_matrix = matrix[ matrix % 2 == 1 ]
new_matrix

array([5, 9, 9, 1, 5, 7, 9, 7, 7, 3, 1])

MINI CHALLENGE #5:

In the following matrix, replace negative elements by 0 and replace odd elements with -2

In [66]:
X = np.array([
    [2, 30, 20, -2, 4],
    [3, 4, 40, -3, -2],
    [-3, 4, -6, 90,10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])
X

array([[ 2, 30, 20, -2,  4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [13, 24, 22, 32, 37]])

In [67]:
X[X < 0] = 0
X

array([[ 2, 30, 20,  0,  4],
       [ 3,  4, 40,  0,  0],
       [ 0,  4,  0, 90, 10],
       [25, 45, 34, 22, 12],
       [13, 24, 22, 32, 37]])

In [68]:
X[X % 2 == 1] = -2
X

array([[ 2, 30, 20,  0,  4],
       [-2,  4, 40,  0,  0],
       [ 0,  4,  0, 90, 10],
       [-2, -2, 34, 22, 12],
       [-2, 24, 22, 32, -2]])

# TASK #6: UNDERSTAND PANDAS FUNDAMENTALS

In [ ]:
# Pandas is a data manipulation and analysis tool that is built on Numpy.
# Pandas uses a data structure known as DataFrame (think of it as Microsoft excel in Python).
# DataFrames empower programmers to store and manipulate data in a tabular fashion (rows and columns).
# Series Vs. DataFrame? Series is considered a single column of a DataFrame.

In [72]:
import pandas as pd

In [74]:
bank_client_df = pd.DataFrame({'Bank Client ID': [111, 222, 333, 444],
                               'Bank Client Name': ['Chanel', 'Steve', 'Mitch', 'Ryan'],
                               'Net Worth [$]': [3500, 29000, 10000, 2000],
                               'Years with bank': [3, 4, 9, 5]})
bank_client_df

Bank Client ID Bank Client Name  Net Worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [75]:
type(bank_client_df)

pandas.core.frame.DataFrame

In [77]:
bank_client_df.head(2)

Bank Client ID Bank Client Name  Net Worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4

In [78]:
bank_client_df.tail(2)

Bank Client ID Bank Client Name  Net Worth [$]  Years with bank
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [79]:
portfolio_df = pd.DataFrame({ 'Ticker': ['AAPL', 'AMZN', 'T'],
                              'Price per share [$]': [3500, 200, 40],
                              'Number of stocks': [3, 4, 9]})
portfolio_df

Ticker  Price per share [$]  Number of stocks
0   AAPL                 3500                 3
1   AMZN                  200                 4
2      T                   40                 9

In [80]:
stocks_dollar_value = portfolio_df['Price per share [$]'] * portfolio_df['Number of stocks']
stocks_dollar_value

0    10500
1      800
2      360
dtype: int64

In [81]:
stocks_dollar_value.sum()

11660

# TASK #7: PANDAS WITH CSV AND HTML DATA

In [5]:
!pip3 install lxml

DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
You should consider upgrading via the '/usr/local/opt/python@3.9/bin/python3.9 -m pip install --upgrade pip' command.


In [1]:
import pandas as pd

In [5]:
house_price_df = pd.read_html('https://www.livingin-canada.com/house-prices-canada.html')
house_price_df[0]

City  \
0                                      Vancouver, BC   
1                                       Toronto, Ont   
2                                        Ottawa, Ont   
3                                       Calgary, Alb   
4                                      Montreal, Que   
5                                        Halifax, NS   
6                                       Regina, Sask   
7                                    Fredericton, NB   
8  (adsbygoogle = window.adsbygoogle || []).push(...   

                                 Average House Price  \
0                                         $1,036,000   
1                                           $870,000   
2                                           $479,000   
3                                           $410,000   
4                                           $435,000   
5                                           $331,000   
6                                           $254,000   
7                                           $198,000   
8  (adsbygoogle = window.adsbygoogle || []).push(...   

                                     12 Month Change  
0                                           + 2.63 %  
1                                            +10.2 %  
2                                           + 15.4 %  
3                                            – 1.5 %  
4                                            + 9.3 %  
5                                            + 3.6 %  
6                                            – 3.9 %  
7                                            – 4.3 %  
8  (adsbygoogle = window.adsbygoogle || []).push(...

In [6]:
house_price_df[1]

Province  \
0                                    British Columbia   
1                                             Ontario   
2                                             Alberta   
3                                              Quebec   
4                                            Manitoba   
5                                        Saskatchewan   
6                                         Nova Scotia   
7                                Prince Edward Island   
8                             Newfoundland / Labrador   
9                                       New Brunswick   
10                                   Canadian Average   
11  (adsbygoogle = window.adsbygoogle || []).push(...   

                                  Average House Price  \
0                                            $736,000   
1                                            $594,000   
2                                            $353,000   
3                                            $340,000   
4                                            $295,000   
5                                            $271,000   
6                                            $266,000   
7                                            $243,000   
8                                            $236,000   
9                                            $183,000   
10                                           $488,000   
11  (adsbygoogle = window.adsbygoogle || []).push(...   

                                      12 Month Change  
0                                             + 7.6 %  
1                                             – 3.2 %  
2                                             – 7.5 %  
3                                             + 7.6 %  
4                                             – 1.4 %  
5                                             – 3.8 %  
6                                             + 3.5 %  
7                                             + 3.0 %  
8                                             – 1.6 %  
9                                             – 2.2 %  
10                                            – 1.3 %  
11  (adsbygoogle = window.adsbygoogle || []).push(...

In [7]:
house_price_df[2]

IndexError: list index out of range

In [8]:
retirement_df = pd.read_html('https://www.ssa.gov/oact/progdata/nra.html')
retirement_df[0]

Year of birth  \
0                                      1937 and prior   
1                                                1938   
2                                                1939   
3                                                1940   
4                                                1941   
5                                                1942   
6                                             1943-54   
7                                                1955   
8                                                1956   
9                                                1957   
10                                               1958   
11                                               1959   
12                                     1960 and later   
13  Notes: 1. Persons born on January 1 of any yea...   

                                                  Age  
0                                                  65  
1                                     65 and 2 months  
2                                     65 and 4 months  
3                                     65 and 6 months  
4                                     65 and 8 months  
5                                    65 and 10 months  
6                                                  66  
7                                     66 and 2 months  
8                                     66 and 4 months  
9                                     66 and 6 months  
10                                    66 and 8 months  
11                                   66 and 10 months  
12                                                 67  
13  Notes: 1. Persons born on January 1 of any yea...

IndexError: list index out of range

# TASK #8: PANDAS OPERATIONS

In [10]:
bank_client_df = pd.DataFrame({'Bank Client ID': [111, 222, 333, 444],
                               'Bank Client Name': ['Chanel', 'Steve', 'Mitch', 'Ryan'],
                               'Net Worth [$]': [3500, 29000, 10000, 2000],
                               'Years with bank': [3, 4, 9, 5]})
bank_client_df

Bank Client ID Bank Client Name  Net Worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [12]:
df_loyal = bank_client_df[ bank_client_df['Years with bank'] >= 5 ]
df_loyal

Bank Client ID Bank Client Name  Net Worth [$]  Years with bank
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [13]:
# Delete a column from a DataFrame
del bank_client_df['Bank Client ID']
bank_client_df

Bank Client Name  Net Worth [$]  Years with bank
0           Chanel           3500                3
1            Steve          29000                4
2            Mitch          10000                9
3             Ryan           2000                5

In [14]:
high_networth_df = bank_client_df[bank_client_df['Net Worth [$]'] >= 5000]
high_networth_df

Bank Client Name  Net Worth [$]  Years with bank
1            Steve          29000                4
2            Mitch          10000                9

In [16]:
high_networth_sum = high_networth_df['Net Worth [$]'].sum()
high_networth_sum

39000

# TASK #9: PANDAS WITH FUNCTIONS

In [23]:
bank_client_df = pd.DataFrame({'Bank Client ID': [111, 222, 333, 444],
                               'Bank Client Name': ['Chanel', 'Steve', 'Mitch', 'Ryan'],
                               'Net Worth [$]': [3500, 29000, 10000, 2000],
                               'Years with bank': [3, 4, 9, 5]})
bank_client_df

Bank Client ID Bank Client Name  Net Worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [24]:
# Increase clients networth by a fixed value of 20%
def networth_update(balance):
    return balance * 1.2

In [25]:
# Apply a function to a DataFrame
bank_client_df['Net Worth [$]'].apply(networth_update)

0     4200.0
1    34800.0
2    12000.0
3     2400.0
Name: Net Worth [$], dtype: float64

In [26]:
bank_client_df['Bank Client Name'].apply(len)

0    6
1    5
2    5
3    4
Name: Bank Client Name, dtype: int64

In [27]:
def networth_bonus(balance):
    return balance * 3 + 200

In [29]:
bonus_df = bank_client_df['Net Worth [$]'].apply(networth_bonus)

In [30]:
bonus_df

0    10700
1    87200
2    30200
3     6200
Name: Net Worth [$], dtype: int64

In [31]:
bonus_df.sum()

134300

# TASK #10: PERFORM SORTING AND ORDERING IN PANDAS

In [33]:
bank_client_df = pd.DataFrame({'Bank Client ID': [111, 222, 333, 444],
                               'Bank Client Name': ['Chanel', 'Steve', 'Mitch', 'Ryan'],
                               'Net Worth [$]': [3500, 29000, 10000, 2000],
                               'Years with bank': [3, 4, 9, 5]})
bank_client_df

Bank Client ID Bank Client Name  Net Worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [34]:
# Sort the values in dataframe, but nothing is changed in memory!
bank_client_df.sort_values(by = 'Years with bank')

Bank Client ID Bank Client Name  Net Worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
3             444             Ryan           2000                5
2             333            Mitch          10000                9

In [35]:
bank_client_df

Bank Client ID Bank Client Name  Net Worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [36]:
# Set inplace = True to apply changes in memory
bank_client_df.sort_values(by='Years with bank', inplace=True)

In [37]:
bank_client_df

Bank Client ID Bank Client Name  Net Worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
3             444             Ryan           2000                5
2             333            Mitch          10000                9

# Task #11: Perform concatenation and merging with pandas

In [38]:
df1 = pd.DataFrame({ 'A': ['A0', 'A1', 'A2', 'A3'],
                     'B': ['B0', 'B1', 'B2', 'B3'],
                     'C': ['C0', 'C1', 'C2', 'C3'],
                     'D': ['D0', 'D1', 'D2', 'D3']},
                   index=[0, 1, 2, 3])

In [39]:
df1

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [40]:
df2 = pd.DataFrame({ 'A': ['A4', 'A5', 'A6', 'A7'],
                     'B': ['B4', 'B5', 'B6', 'B7'],
                     'C': ['C4', 'C5', 'C6', 'C7'],
                     'D': ['D4', 'D5', 'D6', 'D7']},
                   index=[4, 5, 6, 7])

In [41]:
df2

A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [42]:
df3 = pd.DataFrame({ 'A': ['A8', 'A9', 'A10', 'A11'],
                     'B': ['B8', 'B9', 'B10', 'B11'],
                     'C': ['C8', 'C9', 'C10', 'C11'],
                     'D': ['D8', 'D9', 'D10', 'D11']},
                   index=[8, 9, 10, 11])

In [43]:
df3

A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [44]:
pd.concat([df1, df2, df3])

A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

# TASK #12: PROJECT AND CONCLUDING REMARKS

In [45]:
raw_data = {
    'Bank Client ID': ['1', '2', '3', '4', '5'],
    'First Name': ['Nancy', 'Alex', 'Shep', 'Max', 'Allen'],
    'Last Name': ['Rob', 'Ali', 'George', 'Mitch', 'Steve']
}

bank_df_1 = pd.DataFrame(raw_data, columns=['Bank Client ID', 'First Name', 'Last Name'])
bank_df_1

Bank Client ID First Name Last Name
0              1      Nancy       Rob
1              2       Alex       Ali
2              3       Shep    George
3              4        Max     Mitch
4              5      Allen     Steve

In [46]:
raw_data = {
    'Bank Client ID': ['6', '7', '8', '9', '10'],
    'First Name': ['Bill', 'Dina', 'Sarah', 'Heather', 'Holly'],
    'Last Name': ['Christian', 'Mo', 'Steve', 'Rob', 'Michelle']
}

bank_df_2 = pd.DataFrame(raw_data, columns=['Bank Client ID', 'First Name', 'Last Name'])
bank_df_2

Bank Client ID First Name  Last Name
0              6       Bill  Christian
1              7       Dina         Mo
2              8      Sarah      Steve
3              9    Heather        Rob
4             10      Holly   Michelle

In [47]:
raw_data = { 'Bank Client ID': ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'],
             'Annual Salary [$/year]': [25000, 35000, 45000, 48000, 49000, 32000, 33000, 34000, 23000, 22000]}
bank_df_salary = pd.DataFrame(raw_data, columns=['Bank Client ID', 'Annual Salary [$/year]'])
bank_df_salary

Bank Client ID  Annual Salary [$/year]
0              1                   25000
1              2                   35000
2              3                   45000
3              4                   48000
4              5                   49000
5              6                   32000
6              7                   33000
7              8                   34000
8              9                   23000
9             10                   22000

In [48]:
# Concatenate the datasets:
bank_df_all = pd.concat([bank_df_1, bank_df_2])

In [49]:
bank_df_all

Bank Client ID First Name  Last Name
0              1      Nancy        Rob
1              2       Alex        Ali
2              3       Shep     George
3              4        Max      Mitch
4              5      Allen      Steve
0              6       Bill  Christian
1              7       Dina         Mo
2              8      Sarah      Steve
3              9    Heather        Rob
4             10      Holly   Michelle

In [52]:
# merge DF based on bank client ID:
bank_df_all = pd.merge(bank_df_all, bank_df_salary, on='Bank Client ID')

In [53]:
bank_df_all

Bank Client ID First Name  Last Name  Annual Salary [$/year]
0              1      Nancy        Rob                   25000
1              2       Alex        Ali                   35000
2              3       Shep     George                   45000
3              4        Max      Mitch                   48000
4              5      Allen      Steve                   49000
5              6       Bill  Christian                   32000
6              7       Dina         Mo                   33000
7              8      Sarah      Steve                   34000
8              9    Heather        Rob                   23000
9             10      Holly   Michelle                   22000

In [56]:
new_client = { 'Bank Client ID': ['11'],
               'First Name': ['Ryan'],
               'Last Name': ['Ahmed'],
               'Annual Salary [$/year]': [5000]}
new_client_df = pd.DataFrame(new_client, columns=['Bank Client ID', 'First Name', 'Last Name', 'Annual Salary [$/year]'])

In [57]:
new_client_df

Bank Client ID First Name Last Name  Annual Salary [$/year]
0             11       Ryan     Ahmed                    5000

In [58]:
new_df = pd.concat([bank_df_all, new_client_df])
new_df

Bank Client ID First Name  Last Name  Annual Salary [$/year]
0              1      Nancy        Rob                   25000
1              2       Alex        Ali                   35000
2              3       Shep     George                   45000
3              4        Max      Mitch                   48000
4              5      Allen      Steve                   49000
5              6       Bill  Christian                   32000
6              7       Dina         Mo                   33000
7              8      Sarah      Steve                   34000
8              9    Heather        Rob                   23000
9             10      Holly   Michelle                   22000
0             11       Ryan      Ahmed                    5000